spring.application.name=finance managment system

server.forward-headers-strategy=framework


# JWT Config
jwt.secret=TmV3U2VjcmV0S2V5Rm9ySldUU2lnbmluZ1B1cnBvc2VzMTIzNDU2Nzg=
jwt.expiration= 36000000



# # ===============================
# # DATABASE CONFIG
# # ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver



# ===============================
# JPA / HIBERNATE CONFIG
# ===============================
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialecs
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# IMPORTANT Set Default Schema
spring.jpa.properties.hibernate.default_schema=hisab


#Frontend redierct URL
frontend_redirect_url=http://localhost:3000

